var KEY_NUMBERS = {
    MEALS_PER_DAY: 4,
    AVG_MEAL_PRICE: 10,
    HOTEL_COST: 125,
    VAN_FUEL_COST: 2,
    VAN_MPG: 16,
    HOURLY_FEE: 20,
    ENTERPRISE_ROADSIDE_DAILY: 5.99,
    ENTERPRISE_DAILY_FEE: 7,
    ENTERPRISE_MILEAGE_CHARGE: .17,
    TRUCK_FUEL_COST: 2,
    TRUCK_MPG: 10,
    ROUND_TRIP_WAREHOUSE_ENTERPRISE: 28,
    DAILY_MILE_LIMIT: 600
  
  }

  export {KEY_NUMBERS};